spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Houscore-spring
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://admin:OTIJWI2mHbWy0KMoXG@13.124.84.12:27017/admin
  batch:
    job:
      enabled: true # 서버 재시작시 배치 자동실행 방지 = false
      jdbc:
        initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5aa766f4cda38dde20e1ab7b09aa5a35
            client-secret: peEbVlFdvrDjpPnmoZYKyH5TWDCtZ6FD
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id

  cloud:
    aws:
      s3:
        bucket: houscore
      #      folder:
      #        [VARIABLE]: [VALUE]
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt: # base64로 인코딩된 512비트(64바이트) 이상의 키
  access:
    expiration: 36000 # 1초
    header: Authorization
  refresh:
    expiration: 86400000 # 1일
    header: Authorization-refresh

server:
  port: ${SERVER_PORT} # jenkins와 8080 포트 충돌 방지