spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5aa766f4cda38dde20e1ab7b09aa5a35
            client-secret: peEbVlFdvrDjpPnmoZYKyH5TWDCtZ6FD
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id

jwt: # base64로 인코딩된 512비트(64바이트) 이상의 키
  access:
    expiration: 3600000 # 1시간
    header: Authorization
  refresh:
    expiration: 86400000 # 1일
    header: Authorization-refresh