version: '3.8'
services:
  app:
    image: houscore-springboot-app
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  ai_service:
    image: houscore-fastapi-app
    ports:
      - "8000:8000"

